related_topics:
- docker
- kubernetes

title:
  i18n:
    en: Docker

description:
  i18n:
    en: Docker is a widely-used open-source tool for containerization, offering a portable and consistent runtime environment for software applications. It is more resource-efficient compared to traditional servers or virtual machines. Docker operates through containers, which are isolated user-space environments that run at the operating system level and share system resources like the kernel and filesystem.
    ru: Docker — это широко используемый инструмент с открытым исходным кодом для контейнеризации, предлагающий портативную и согласованную среду выполнения для приложений. Он более эффективен в плане ресурсов по сравнению с традиционными серверами или виртуальными машинами. Docker работает через контейнеры, которые представляют собой изолированные пользовательские среды, работающие на уровне операционной системы и совместно использующие системные ресурсы, такие как ядро и файловая система.
