name: Build and Deploy to GitHub Pages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all history so we can check branch info

      - name: Ensure tag is on main branch
        run: |
          # Check if current commit ($GITHUB_SHA) is contained in main
          if ! git branch -r --contains $GITHUB_SHA | grep -q 'origin/main'; then
            echo "Tag is not on main branch. Exiting."
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y rsync imagemagick

      - name: Install npm dependencies
        run: make install

      - name: Build site
        run: |
          make build
          make build-static

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
           # this should match the `pages` option in your adapter-static options
           path: 'frontend/build'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
